/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SaasRouteImport } from './routes/saas'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAjudaRouteImport } from './routes/_authenticated/admin/ajuda'
import { Route as AuthenticatedAdminAlterarSenhaRouteImport } from './routes/_authenticated/admin/alterar-senha'
import { Route as AuthenticatedAdminAparenciaRouteImport } from './routes/_authenticated/admin/aparencia'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin/backup'
import { Route as AuthenticatedAdminBannerRouteImport } from './routes/_authenticated/admin/banner'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin/categorias'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as AuthenticatedAdminMarcaRouteImport } from './routes/_authenticated/admin/marca'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin/produtos'
import { Route as LojaSlugProdutoProductSlugRouteImport } from './routes/loja.$slug.produto.$productSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasRoute = SaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAjudaRoute = AuthenticatedAdminAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAlterarSenhaRoute =
  AuthenticatedAdminAlterarSenhaRouteImport.update({
    id: '/alterar-senha',
    path: '/alterar-senha',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAparenciaRoute =
  AuthenticatedAdminAparenciaRouteImport.update({
    id: '/aparencia',
    path: '/aparencia',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBannerRoute =
  AuthenticatedAdminBannerRouteImport.update({
    id: '/banner',
    path: '/banner',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMarcaRoute = AuthenticatedAdminMarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const LojaSlugProdutoProductSlugRoute =
  LojaSlugProdutoProductSlugRouteImport.update({
    id: '/produto/$productSlug',
    path: '/produto/$productSlug',
    getParentRoute: () => LojaSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saas': typeof SaasRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/ajuda': typeof AuthenticatedAdminAjudaRoute
  '/admin/alterar-senha': typeof AuthenticatedAdminAlterarSenhaRoute
  '/admin/aparencia': typeof AuthenticatedAdminAparenciaRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/banner': typeof AuthenticatedAdminBannerRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/marca': typeof AuthenticatedAdminMarcaRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/loja/$slug/produto/$productSlug': typeof LojaSlugProdutoProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saas': typeof SaasRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/ajuda': typeof AuthenticatedAdminAjudaRoute
  '/admin/alterar-senha': typeof AuthenticatedAdminAlterarSenhaRoute
  '/admin/aparencia': typeof AuthenticatedAdminAparenciaRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/banner': typeof AuthenticatedAdminBannerRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/marca': typeof AuthenticatedAdminMarcaRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/loja/$slug/produto/$productSlug': typeof LojaSlugProdutoProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saas': typeof SaasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/_authenticated/admin/ajuda': typeof AuthenticatedAdminAjudaRoute
  '/_authenticated/admin/alterar-senha': typeof AuthenticatedAdminAlterarSenhaRoute
  '/_authenticated/admin/aparencia': typeof AuthenticatedAdminAparenciaRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/banner': typeof AuthenticatedAdminBannerRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/marca': typeof AuthenticatedAdminMarcaRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/loja/$slug/produto/$productSlug': typeof LojaSlugProdutoProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/saas'
    | '/admin'
    | '/loja/$slug'
    | '/produto/$slug'
    | '/admin/ajuda'
    | '/admin/alterar-senha'
    | '/admin/aparencia'
    | '/admin/backup'
    | '/admin/banner'
    | '/admin/categorias'
    | '/admin/leads'
    | '/admin/marca'
    | '/admin/produtos'
    | '/admin/'
    | '/loja/$slug/produto/$productSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/saas'
    | '/loja/$slug'
    | '/produto/$slug'
    | '/admin/ajuda'
    | '/admin/alterar-senha'
    | '/admin/aparencia'
    | '/admin/backup'
    | '/admin/banner'
    | '/admin/categorias'
    | '/admin/leads'
    | '/admin/marca'
    | '/admin/produtos'
    | '/admin'
    | '/loja/$slug/produto/$productSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/saas'
    | '/_authenticated/admin'
    | '/loja/$slug'
    | '/produto/$slug'
    | '/_authenticated/admin/ajuda'
    | '/_authenticated/admin/alterar-senha'
    | '/_authenticated/admin/aparencia'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/banner'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/marca'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/'
    | '/loja/$slug/produto/$productSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SaasRoute: typeof SaasRoute
  LojaSlugRoute: typeof LojaSlugRouteWithChildren
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas': {
      id: '/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof SaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ajuda': {
      id: '/_authenticated/admin/ajuda'
      path: '/ajuda'
      fullPath: '/admin/ajuda'
      preLoaderRoute: typeof AuthenticatedAdminAjudaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/alterar-senha': {
      id: '/_authenticated/admin/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/admin/alterar-senha'
      preLoaderRoute: typeof AuthenticatedAdminAlterarSenhaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/aparencia': {
      id: '/_authenticated/admin/aparencia'
      path: '/aparencia'
      fullPath: '/admin/aparencia'
      preLoaderRoute: typeof AuthenticatedAdminAparenciaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/banner': {
      id: '/_authenticated/admin/banner'
      path: '/banner'
      fullPath: '/admin/banner'
      preLoaderRoute: typeof AuthenticatedAdminBannerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/marca': {
      id: '/_authenticated/admin/marca'
      path: '/marca'
      fullPath: '/admin/marca'
      preLoaderRoute: typeof AuthenticatedAdminMarcaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/loja/$slug/produto/$productSlug': {
      id: '/loja/$slug/produto/$productSlug'
      path: '/produto/$productSlug'
      fullPath: '/loja/$slug/produto/$productSlug'
      preLoaderRoute: typeof LojaSlugProdutoProductSlugRouteImport
      parentRoute: typeof LojaSlugRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAjudaRoute: typeof AuthenticatedAdminAjudaRoute
  AuthenticatedAdminAlterarSenhaRoute: typeof AuthenticatedAdminAlterarSenhaRoute
  AuthenticatedAdminAparenciaRoute: typeof AuthenticatedAdminAparenciaRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminBannerRoute: typeof AuthenticatedAdminBannerRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMarcaRoute: typeof AuthenticatedAdminMarcaRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAjudaRoute: AuthenticatedAdminAjudaRoute,
    AuthenticatedAdminAlterarSenhaRoute: AuthenticatedAdminAlterarSenhaRoute,
    AuthenticatedAdminAparenciaRoute: AuthenticatedAdminAparenciaRoute,
    AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
    AuthenticatedAdminBannerRoute: AuthenticatedAdminBannerRoute,
    AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
    AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
    AuthenticatedAdminMarcaRoute: AuthenticatedAdminMarcaRoute,
    AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LojaSlugRouteChildren {
  LojaSlugProdutoProductSlugRoute: typeof LojaSlugProdutoProductSlugRoute
}

const LojaSlugRouteChildren: LojaSlugRouteChildren = {
  LojaSlugProdutoProductSlugRoute: LojaSlugProdutoProductSlugRoute,
}

const LojaSlugRouteWithChildren = LojaSlugRoute._addFileChildren(
  LojaSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SaasRoute: SaasRoute,
  LojaSlugRoute: LojaSlugRouteWithChildren,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}